### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by TheFelin** [kepon85/PvMonit#3]
Est-il possible à partir de PHP d'avoir les informations du contrôleur connecté en Bluetooth?

**Comment by kepon85** [comment]
Aucune idée, j'ai jamais vu ça.
De ce que j'en sais ça semble pas simple. A mon avis c'est tout aussi simple de connecter un arduino avec un câble sur le contrôleur (ça c'est documenté) et que l'arduino émette en bluetooth si tu tiens absolument au bluetooth...
